GET http://localhost:8080/api/v2/beer/1
#POST http://localhost:8080/api/v2/beer
#PUT http://localhost:8080/api/v2/beer/1
#PATCH http://localhost:8080/api/v2/beer/1
Accept: application/json
Content-Type: application/json

{
  "quantityOnHand": 3
}